version: "3.3"

services:
  skade-db:
    container_name: skade-db
    image: postgres:12.3-alpine
    env_file:
      - env/postgres.env
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    ports:
    - target: 5432
      published: 5432


volumes:
  postgres_data: